name: pizzy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^10.1.0
  
  geocoder2: ^1.1.0
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3
  google_sign_in: ^5.3.0
  lottie: ^1.2.2
  page_transition: ^2.0.5
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - animations/pizza.json
  #   - images/a_dot_ham.jpeg
